refresh:

set_log_level:
  fields:
    level:
      required: true
      default: debug
      example: debug
      selector:
        select:
          options:
            - "debug"
            - "info"
            - "warning"
            - "error"

set_mqtt_log_level:
  fields:
    level:
      required: true
      default: debug
      example: debug
      selector:
        select:
          options:
            - "debug"
            - "info"
            - "warning"
            - "error"

send_command:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: addhon
    command:
      required: true
      default: settings
      example: settings
      selector:
        text:
    parameters:
      required: true
      example: '{"operationName": "grSetVacDate", "vacStartDate": "2026-09-01"}'
      selector:
        object:

probe_settings_operation:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: addhon
    parameter:
      required: true
      example: sterilizationTime
      selector:
        text:
    value:
      required: true
      example: "07:00"
      selector:
        text:
    command:
      required: false
      default: settings
      selector:
        text:
    operations:
      required: false
      example: '["grSetSterilizationTime", "grSetSterilization"]'
      selector:
        object:
    settle:
      required: false
      default: 12
      selector:
        number:
          min: 3
          max: 60
          unit_of_measurement: s
